package ro.edu.fmi.tss;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

class TriangleClassifierAIGeneratedTest {

    @Test
    void autoGeneratedShouldRecognizeEquilateralTriangle() {
        assertEquals(TriangleType.EQUILATERAL, TriangleClassifier.classify(10, 10, 10));
    }

    @Test
    void autoGeneratedShouldRejectNegativeSides() {
        assertFalse(TriangleClassifier.isValidTriangle(-3, 4, 5));
        assertEquals(TriangleType.INVALID, TriangleClassifier.classify(-3, 4, 5));
    }

    @Test
    void autoGeneratedShouldHandleLargeRightTriangle() {
        assertTrue(TriangleClassifier.isRightTriangle(20, 21, 29));
        assertEquals(TriangleType.RIGHT_SCALENE, TriangleClassifier.classify(20, 21, 29));
    }

    @Test
    void autoGeneratedShouldComputePerimeterCorrectly() {
        assertEquals(12, TriangleClassifier.perimeter(3, 4, 5));
    }

    @Test
    void autoGeneratedShouldNotClassifyImpossibleShape() {
        assertEquals(TriangleType.INVALID, TriangleClassifier.classify(2, 2, 5));
    }
}
